<a href="https://colab.research.google.com/github/Md-Refat-Hosain/practice-ML-models/blob/main/Iris_classify_with_SVM_(cdm).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Iris data set classify with SVM

In [ ]:
# Import all the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import statistics as st

# Libraries For Text

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')



from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import confusion_matrix
%matplotlib inline

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# import Iris dataset

In [2]:
from sklearn import  datasets

In [3]:
iris = datasets.load_iris()

In [ ]:
# divide the data into 2 variables

In [4]:
X = iris.data
y = iris.target

In [ ]:
# split data for train and test

In [5]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size= .3 , random_state= 42 , stratify= y)

In [ ]:
# import SVC and CONFUSION MATRICS

In [6]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [ ]:
# with the 'rbf' kernel and gamma 1.0

In [7]:
svc = SVC(kernel = 'rbf' , gamma = 1.0)

svc.fit(X_train , y_train)
y_preds = svc.predict(X_test)

In [8]:
cm_rbf01 = confusion_matrix(y_test , y_preds)
cm_rbf01

array([[15,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 14]])

In [ ]:
# with the 'rbf' kernel and gamma 1.0 (2 fault prediction)

In [9]:
svc = SVC(kernel = 'rbf' , gamma = 10.0)

svc.fit(X_train , y_train)
y_preds = svc.predict(X_test)

cm_rbf10 = confusion_matrix(y_test , y_preds)
cm_rbf10

array([[13,  0,  2],
       [ 0, 15,  0],
       [ 0,  1, 14]])

In [ ]:
# Linear SVC kernel (best performer with zero fault prediction)

In [10]:
svc = SVC(kernel='linear')
svc.fit(X_train , y_train)
y_preds = svc.predict(X_test)
cm_linear = confusion_matrix(y_test , y_preds)
cm_linear

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 15]])

In [ ]:
 # plynomial SVC kernel (1 fault prediction)

In [11]:
svc = SVC(kernel='poly')
svc.fit(X_train , y_train)
y_preds = svc.predict(X_test)
cm_poly = confusion_matrix(y_test , y_preds)
cm_poly

array([[15,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 14]])

In [ ]:
# sigmoid SVC kernel (14 fault prediction , worst performer)

In [12]:
svc = SVC(kernel='sigmoid')
svc.fit(X_train , y_train)
y_preds = svc.predict(X_test)
cm_sigm = confusion_matrix(y_test , y_preds)
cm_sigm

array([[ 1,  0, 14],
       [ 8,  0,  7],
       [14,  0,  1]])